# nothing here
CONFIG_STDOUT_CONSOLE=y
CONFIG_UART_ASYNC_API=y 
CONFIG_ADC=y
CONFIG_CAN=y
CONFIG_CAN_MCP2515=y
CONFIG_SPI=y
CONFIG_NEWLIB_LIBC=y 
#CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y 
CONFIG_SERIAL=y   
CONFIG_UART_INTERRUPT_DRIVEN=y

# Bluetooth
CONFIG_BT=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_GATT_CLIENT=y
CONFIG_BT_HCI=y

# Enable scanning
CONFIG_BT_OBSERVER=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# Memory
CONFIG_HEAP_MEM_POOL_SIZE=2048
